# Pipeline definition for CD after the CI pipeline runs.
trigger: none

resources:
  pipelines:
    - pipeline: az-vote-ci
      source: "arc-cicd-demo-src CI"
      trigger:
        branches:
        # Until Flux V2 integration is in Public Preview, work with FluxV2 branch.
        # Once Flux V2 integration is in Public Preview, FluxV2 branch will be merged into the default branch.
          - FluxV2
  repositories:
    - repository: Manifest
      type: git
      name: arc-cicd-demo-gitops

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: az-vote-app-dev
  - name: images_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/image_tags
  - name: manifests_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/manifests
  - name: utils_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/utils

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "deploy_dev"
    displayName: "Deploy to Dev"
    jobs:
      - deployment: Deploy_to_dev
        displayName: "Deploy to Dev"
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deployment-template.yaml
    
      - job: deploy_with_gitops
        dependsOn: Deploy_to_dev
        displayName: Wait for changes to be applied
        pool: server          
        variables:
          pr_num: $[ dependencies.Deploy_to_dev.outputs['Deploy_to_dev.Create_PR.PR_NUM'] ]
        condition: ne(variables['pr_num'],'')
        steps:   
        - template: pr-completion-task-template.yaml                 

      - job: "Automated_testing"
        displayName: Automated testing 
        dependsOn: deploy_with_gitops
        steps:
        - template: post-deployment-test-template.yaml


  - stage: "deploy_stage"
    displayName: "Deploy to Stage"
    variables:
      - group: az-vote-app-stage
    jobs:
      - deployment: Deploy_to_stage
        displayName: "Deploy to Stage"
        environment: stage
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deployment-template.yaml

      - job: deploy_with_gitops
        dependsOn: Deploy_to_stage
        displayName: Wait for changes to be applied
        pool: server          
        variables:
          pr_num: $[ dependencies.Deploy_to_stage.outputs['Deploy_to_stage.Create_PR.PR_NUM'] ]
        condition: ne(variables['pr_num'],'')        
        steps:   
        - template: pr-completion-task-template.yaml  

      - job: "Automated_testing"
        displayName: Automated testing 
        dependsOn: deploy_with_gitops
        steps:
        - template: post-deployment-test-template.yaml